Fe update scan page API
canada-ca/tracker pull request #1515
Opened 2021-01-25 13:48 UTC by lcampbell2

update Scan details dage to js-api
![Screenshot from 2021-01-25 09-48-05](https://user-images.githubusercontent.com/64781228/105714243-7bf9d800-5ef2-11eb-925a-ea21fe8c3909.png)
![Screenshot from 2021-01-25 09-48-15](https://user-images.githubusercontent.com/64781228/105714254-7dc39b80-5ef2-11eb-9986-24c547b88bc7.png)

2021-01-25 18:41 UTC, tparrott-cse reviewed
In the first image you have web scan with email results...?

2021-01-25 22:29 UTC, sleepycat approved these changes
:tada:  Nice!

2021-01-25 22:39 UTC, FestiveKyle requested changes

2021-01-25 22:39 UTC, FestiveKyle commented on frontend/src/graphql/queries.js
> +              results {
results need pagination arguments

2021-01-26 13:00 UTC, lcampbell2 commented
> In the first image you have web scan with email results...?

Faker only provided tags for dkim, I'll update the pics with real results

2021-01-26 15:55 UTC, FestiveKyle approved these changes
Great stuff 🔥

2021-01-26 17:08 UTC, merged