Update User Password Union Introduction
canada-ca/tracker pull request #1794
Opened 2021-03-05 14:04 UTC by nsdeschenes

Union introduction for handling soft errors when users attempt to update their password with the `updateUserPassword` mutation.

Mutation Example:
```graphql
mutation {
  updateUserPassword(
    input: {
      currentPassword: ""
      updatedPassword: ""
      updatedPasswordConfirm: ""
    }
  ) {
    result {
      ... on UpdateUserPasswordResultType {
        status
      }
      ... on UpdateUserPasswordError {
        code
        description
      }
    }
  }
}

```

2021-03-05 14:26 UTC, Ethanljf approved these changes

2021-03-05 18:34 UTC, FestiveKyle requested changes

2021-03-05 18:34 UTC, FestiveKyle commented on frontend/src/EditableUserPassword.js
> +          updateUserPassword.result.__typeName ===
```suggestion
          updateUserPassword.result.__typename ===
```

2021-03-05 18:34 UTC, FestiveKyle commented on frontend/src/EditableUserPassword.js
> +          updateUserPassword.result.__typeName === 'UpdateUserPasswordError'
```suggestion
          updateUserPassword.result.__typename === 'UpdateUserPasswordError'
```

2021-03-08 13:46 UTC, lcampbell2 approved these changes

2021-03-09 13:13 UTC, FestiveKyle approved these changes

2021-03-09 13:20 UTC, merged