Fe fix phone number validation
canada-ca/tracker pull request #1847
Opened 2021-03-11 17:15 UTC by ThomasNickerson

This PR closes issue #1685 by adding validation of phone numbers with regex on the front end according to the format specified in API docs.

2021-03-12 10:39 UTC, nsdeschenes requested changes
You're missing the compiled locale files all you gotta do is run `npm run compile` and add them to git, and we'll be good to go!

2021-03-12 16:47 UTC, FestiveKyle approved these changes

2021-03-15 09:32 UTC, nsdeschenes approved these changes

2021-03-15 12:13 UTC, tparrott-cse approved these changes
Approved pending resolution of Nick's comment

2021-03-15 12:50 UTC, lcampbell2 approved these changes

2021-03-15 13:53 UTC, ThomasNickerson commented
> Approved pending resolution of Nick's comment

Compiled locale files were added in 7f824ec155d073ecdd75dcb0eaf849e70975c1a6 which should resolve that issue.

2021-03-15 18:56 UTC, merged