Add OrderBy faker results to web and email categories
canada-ca/tracker pull request #1963
Opened 2021-03-24 13:31 UTC by lcampbell2

adds orderby options for HTTPS, SSL, DKIM, DMARC, and SPF

2021-03-25 12:58 UTC, nsdeschenes requested changes

2021-03-25 12:58 UTC, nsdeschenes commented on frontend/schema.faker.graphql
> +
Can you remove the extra new lines, just to keep things consistent.

2021-03-25 14:22 UTC, FestiveKyle approved these changes

2021-03-26 09:30 UTC, nsdeschenes approved these changes

2021-03-26 13:02 UTC, merged