Verify Account Through Link
canada-ca/tracker pull request #2171
Opened 2021-05-05 17:14 UTC by lcampbell2

Resolves #2018 

Adds in page linked from verification emails that uses `verifyAccount` mutation to do as such for users

![Screenshot from 2021-05-05 14-09-21](https://user-images.githubusercontent.com/64781228/117181416-97a33300-adab-11eb-9ae4-7ea1f5af86c8.png)

`Verify Email` button added to User Page that manually sends email containing link if account has not been verified

![Screenshot from 2021-05-05 14-08-28](https://user-images.githubusercontent.com/64781228/117181393-9114bb80-adab-11eb-8837-f6173c0a3dc7.png)

2021-05-06 09:19 UTC, nsdeschenes requested changes

2021-05-06 09:19 UTC, nsdeschenes commented on frontend/src/App.js
> +// const QRcodePage = lazy(() => import('./QRcodePage'))
This can probably just be straight up removed, I don't believe we are going to use the QR code again.

2021-05-06 11:48 UTC, nsdeschenes requested changes

2021-05-06 11:48 UTC, nsdeschenes commented on frontend/src/EmailValidationPage.js
> +            <Trans>Your account email was successfully verified</Trans>
Can a `home` button be put here, just to give a super duper clear way for what the user needs to do next?

2021-05-06 11:48 UTC, nsdeschenes commented on frontend/src/EmailValidationPage.js
> +          <Text fontSize="xl" textAlign="center">
And maybe a `home` button here as well, something to give the user something extremely clear on where to go next.

2021-05-06 14:56 UTC, nsdeschenes requested changes

2021-05-07 08:57 UTC, nsdeschenes approved these changes
![](https://media.giphy.com/media/KIxBn0rcMbhII/giphy.gif)

2021-05-07 13:12 UTC, FestiveKyle approved these changes

2021-05-07 14:46 UTC, merged