Reverse order of create account buttons (#2368)
canada-ca/tracker pull request #2369
Opened 2021-06-04 10:58 UTC by AdamPrins

Create account was on the left, and the back button was on the right. This original ordering is unintuitive.

2021-06-04 11:15 UTC, AdamPrins commented
Uses new TrackerButton variant from #2372

2021-06-07 12:14 UTC, FestiveKyle approved these changes

2021-06-07 12:19 UTC, FestiveKyle requested changes

2021-06-07 12:19 UTC, FestiveKyle commented on frontend/src/CreateUserPage.js
> +              </TrackerButton>
This Button needs:
```
import { Link as RouteLink } from 'react-router-dom'

as={RouteLink}
```

2021-06-07 12:35 UTC, FestiveKyle approved these changes

2021-06-07 12:36 UTC, merged