DMARC not consistently denoted by failures
canada-ca/tracker pull request #2374
Opened 2021-06-04 11:25 UTC by AdamPrins

Most locations marked what control failed,
But the DMARC graphs marked which control passed

All locations now go by the failure to be consistent.

2021-06-07 13:02 UTC, FestiveKyle requested changes
Translations need to be updated in the locales/*.po files. Default translation entries can be generated in these files by running `npm run extract` as long as the text to be translated exists inside either a \<Trans /> tag or t``

2021-06-07 14:49 UTC, FestiveKyle requested changes

2021-06-07 14:49 UTC, FestiveKyle commented on frontend/src/DmarcReportPage.js
> +          displayName: t`Fail SPF`,
These fields need their 'name' properties to stay 'passSpfOnly' and 'passDkimOnly'. These names come from the API. The display names are good though!

2021-06-08 12:54 UTC, FestiveKyle commented
I fixed the merge conflict here. The locales make for some annoying conflicts sometimes, it wasn't bad this time though

2021-06-08 12:56 UTC, AdamPrins commented
Thanks, I appreciate it.
Good to merge after the tests then?

2021-06-08 12:56 UTC, FestiveKyle approved these changes
👍

2021-06-08 12:57 UTC, merged