Add a shared id for matching one-time-scans together
canada-ca/tracker pull request #2582
Opened 2021-07-05 15:32 UTC by FestiveKyle

As described

2021-07-05 15:42 UTC, nsdeschenes requested changes
Need the tests for keeping that sweet sweet coverage up!

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/email-scan/objects/dkim-sub.js
> +      // TODO type: ID_TYPE,
`type: GraphQLID`

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/email-scan/objects/dkim-sub.js
> +      resolve: async ({ sharedId }) => sharedId,
No async needed

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/email-scan/objects/dmarc-sub.js
> +      // TODO type: ID_TYPE,
:point_up:

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/email-scan/objects/dmarc-sub.js
> +      resolve: async ({ sharedId }) => sharedId,
:point_up:

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/email-scan/objects/spf-sub.js
> +      // TODO type: ID_TYPE,
:point_up:

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/email-scan/objects/spf-sub.js
> +      resolve: async ({ sharedId }) => sharedId,
:point_up:

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/web-scan/objects/https-sub.js
> +      // TODO type: ID_TYPE,
:point_up:

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/web-scan/objects/https-sub.js
> +      resolve: async ({ sharedId }) => sharedId,
:point_up:

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/web-scan/objects/ssl-sub.js
> +      // TODO type: ID_TYPE,
:point_up:

2021-07-05 15:42 UTC, nsdeschenes commented on api-js/src/web-scan/objects/ssl-sub.js
> +      resolve: async ({ sharedId }) => sharedId,
:point_up:

2021-07-05 16:29 UTC, Ethanljf approved these changes
🔥

2021-07-05 16:37 UTC, ThomasNickerson approved these changes

2021-07-06 12:52 UTC, nsdeschenes approved these changes

2021-07-06 13:06 UTC, merged