Add one time scans to the frontend
canada-ca/tracker pull request #2617
Opened 2021-07-12 20:33 UTC by FestiveKyle

Adds individual scan cards for one time scans. These components should be refactored for abstraction use with ScanCard in the future.

![image](https://user-images.githubusercontent.com/47400288/125351990-221d8b00-e337-11eb-8e22-f25224934cd9.png)

![image](https://user-images.githubusercontent.com/47400288/125352020-28136c00-e337-11eb-8297-6062bc0eeab0.png)

![image](https://user-images.githubusercontent.com/47400288/125352028-2b0e5c80-e337-11eb-89b6-de9feecedbcb.png)

2021-07-22 15:35 UTC, sleepycat requested changes
Looks good but we're baking some assumptions about urls in there! Update those and we're good!

2021-07-22 15:35 UTC, sleepycat commented on frontend/src/client.js
> +      : '/graphql',
Tracker is going to be deployed at https://tracker.canada.ca and is currently running at https://staging.tracker.canada.ca and https://tracker.ops.cyber.gc.ca as well as our GCP environment at https://tracker.alpha.canada.ca.
I think leaving this at `/graphql` is probably a good idea.

2021-07-22 15:35 UTC, sleepycat commented on frontend/src/client.js
> +      : 'ws:localhost:3000/graphql',
Same as above.

2021-07-22 19:16 UTC, sleepycat approved these changes
Nice! :star_struck:

2021-07-26 14:22 UTC, lcampbell2 approved these changes
![](https://media.giphy.com/media/3o8doT9BL7dgtolp7O/giphy.gif)

2021-07-26 16:53 UTC, merged