Remove ability to change selectors
canada-ca/tracker pull request #5357
Opened 2024-06-03 18:38 UTC by FestiveKyle

2024-06-04 13:40 UTC, FestiveKyle commented
Before merging, make following changes:
- Update /Guidance section for DKIM selector changes (no adding/editing/removing)
- Add temporary banner with similar info from /Guidance DKIM selector section

2024-06-11 19:08 UTC, lcampbell2 requested changes

2024-06-11 19:08 UTC, lcampbell2 commented on frontend/src/app/ReadGuidancePage.js
> +          <ListItem id="dkimSelectors">
since this is used in the url, can we change this id to kebab case?

2024-06-12 11:28 UTC, lcampbell2 approved these changes

2024-06-12 13:20 UTC, merged