Switch to jetstream
canada-ca/tracker pull request #5457
Opened 2024-07-08 20:13 UTC by FestiveKyle

2024-07-15 17:15 UTC, lcampbell2 requested changes

2024-07-15 17:15 UTC, lcampbell2 commented on scanners/dns-scanner/service.py
> +from nats.errors import TimeoutError
unused import - see line 274. Maybe import with alias (NatsTimeoutError)?

2024-07-15 17:15 UTC, lcampbell2 commented on scanners/web-processor/service.py
> +from concurrent.futures import ThreadPoolExecutor
unused import - see line 350

2024-07-15 17:15 UTC, lcampbell2 commented on scanners/web-processor/service.py
> +from nats.errors import TimeoutError
unused import - see line 371

2024-07-15 17:15 UTC, lcampbell2 commented on scanners/web-scanner/service.py
> +from nats.errors import TimeoutError
unused import - see line 233. import as alias?

2024-07-15 18:42 UTC, FestiveKyle commented on azure-defender-easm/add-domain-to-easm/service.py
> +        ],
Just need to add them all for setup. Adding the stream fails if the configs don't match to the current state.

2024-07-15 19:06 UTC, lcampbell2 commented on azure-defender-easm/add-domain-to-easm/service.py
> +        ],
:+1:

2024-07-24 12:09 UTC, lcampbell2 approved these changes

2024-07-25 15:37 UTC, merged