Remove preferred lang
canada-ca/tracker pull request #5771
Opened 2024-10-04 15:00 UTC by FestiveKyle

Remove features to add/change preferred language and any usage of preferred language.

Reworks username update flow from:
- Change username in UI
- Username gets updated in DB. Email validation is changed to false.
- Email validation email is sent. 
- Following link sets email validation to true.

To:
- Change username in UI
- Username not updated. Email validation is not changed.
- Email validation is sent.
- Email validation email is sent.
- Following link sets username to new email and sets validation to true.

2024-10-04 20:25 UTC, lcampbell2 requested changes

2024-10-04 20:25 UTC, lcampbell2 commented on frontend/package.json
> +    "build": "webpack --env development --config webpack.config.js",
should stay production

2024-10-04 20:36 UTC, FestiveKyle commented on frontend/package.json
> +    "build": "webpack --env development --config webpack.config.js",
Oof good one

2024-10-07 13:14 UTC, lcampbell2 approved these changes

2024-10-07 15:19 UTC, merged